# Copyright Hewlett Packard Enterprise Development LP.

services:
  chapel-dev:
    build:
      context: .
      dockerfile: Containerfile
    container_name: chapel-dev
    stdin_open: true
    tty: true
    volumes:
      - ../:/workspace
    working_dir: /workspace
