# Copyright Hewlett Packard Enterprise Development LP.

services:
  fastotf2-dev:
    image: localhost/fastotf2:latest
    build:
      context: .
    container_name: fastotf2-dev
    stdin_open: true
    tty: true
    volumes:
      - ../:/workspace
    working_dir: /workspace
