[brick]
authors = ["Shreyas Khandekar"]
chplVersion = "2.9.0..2.9.0"
compopts = ["-M../../src"]
copyrightYear = "2026"
license = "Apache-2.0"
name = "FastOTF2Converter"
source = "https://github.com/hpc-ai-adv-dev/fastotf2"
type = "application"
version = "0.1.0"

[dependencies]
Parquet = { git = "https://github.com/e-kayrakli/Parquet" }
# FastOTF2 = { git = "../../" }

[system]
otf2 = "3.1.1"

[examples]
examples = ["FastOTF2ConverterSerial.chpl"]

[tests]
tests = ["StrategyParquetParityTest.chpl", "CallgraphParityTest.chpl", "MetricsParityTest.chpl"]
