[brick]
authors = ["Shreyas Khandekar"]
chplVersion = "2.9.0..2.9.0"
compopts = ["-M../../src"]
copyrightYear = "2026"
license = "Apache-2.0"
name = "FastOTF2Converter"
source = "https://github.com/hpc-ai-adv-dev/fastotf2"
type = "application"
version = "0.1.0"

[dependencies]
Parquet = { git = "https://github.com/chapel-lang/Parquet" }
# Waiting on https://github.com/chapel-lang/chapel/issues/28745 so we can depend on the local FastOTF2 mason library
# Till then we hack it using the -M../../src option in compopts
# FastOTF2 = { path = "../../" }

[system]
otf2 = "3.1.1"

[examples]
examples = ["FastOTF2ConverterSerial.chpl"]

[tests]
tests = ["StrategyParquetParityTest.chpl", "CallgraphParityTest.chpl", "MetricsParityTest.chpl"]
