[brick]
chplVersion = "2.8.0..2.8.0"
compopts = ["-Msrc", "-Mexample", "-M../../src", "-I/opt/otf2/include", "-L/opt/otf2/lib", "-lotf2"]
license = "None"
name = "TraceToCSV"
type = "application"
version = "0.1.0"

[examples]
examples = ["TraceToCSVSerial.chpl"]
